create table coffee_menus (
    id bigint primary key,
    name varchar(100) not null,
    price bigint not null check (price > 0)
);

create table user_points (
    user_id bigint primary key,
    balance bigint not null check (balance >= 0)
);

create table coffee_orders (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    menu_id bigint not null,
    paid_amount bigint not null check (paid_amount > 0),
    ordered_at timestamp with time zone not null
);

create index idx_coffee_orders_ordered_at on coffee_orders (ordered_at);
create index idx_coffee_orders_menu_id_ordered_at on coffee_orders (menu_id, ordered_at);

create table outbox_events (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    menu_id bigint not null,
    paid_amount bigint not null check (paid_amount > 0),
    status varchar(20) not null,
    attempt_count integer not null default 0,
    created_at timestamp with time zone not null,
    claimed_at timestamp with time zone,
    published_at timestamp with time zone
);

create index idx_outbox_events_status_claimed_at on outbox_events (status, claimed_at, id);
